version: '3.8'

services:
  # API Gateway Service
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3000
      - MONGODB_URI=mongodb://mongo:27017/superapp
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=superapp
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JWT_SECRET=development_jwt_secret
    depends_on:
      - mongo
      - postgres
      - redis
    networks:
      - superapp-network
    command: npm run dev

  # MongoDB Service
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - superapp-network

  # PostgreSQL Service
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=superapp
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - superapp-network

  # Redis Service
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - superapp-network

  # Ollama Service (for local AI models)
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    networks:
      - superapp-network

  # Frontend Service (to be implemented)
  # frontend:
  #   build:
  #     context: ./src/frontend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3001:3000"
  #   volumes:
  #     - ./src/frontend:/app
  #     - /app/node_modules
  #   environment:
  #     - NODE_ENV=development
  #     - NEXT_PUBLIC_API_URL=http://api:3000
  #   depends_on:
  #     - api
  #   networks:
  #     - superapp-network
  #   command: npm run dev

networks:
  superapp-network:
    driver: bridge

volumes:
  mongo-data:
  postgres-data:
  redis-data:
  ollama-data: 